filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /hostfs/var/log/audit/audit.log
  pipeline: "auditd-pipeline"

- type: log
  enabled: true
  paths:
    - /hostfs/var/log/syslog
    - /hostfs/var/log/messages
  pipeline: "syslog-pipeline"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

setup.ilm.enabled: false
setup.template.name: "unified-logs"
setup.template.pattern: "unified-logs-*"
setup.template.overwrite: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "unified-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"
